Parsing arguments from the command line
mamkhari/extract_sensor_names pull request #11
Opened 2020-07-28 17:30 UTC by mamkhari

This PR does the following:
- Parses the Command Line Arguments with the Python Argparse module.

2020-07-28 18:37 UTC, mmphego requested changes
I do not think you fully understand how `argparse` really works. Revisit your notes and examples. Also, spend some time watching some YouTube videos for better understanding.

You are on the right path, just need some understanding.

2020-07-29 06:15 UTC, mamkhari commented
@mmphego  Oh, okay. I thought I got is right. This means I can not present about this work, right?

2020-07-29 06:58 UTC, mmphego commented
> @mmphego Oh, okay. I thought I got is right. This means I can not present about this work, right?

You present:
- What you have, 
- How far you went, 
- Obstacles encountered, and
- What you did to overcome them...

2020-07-29 08:03 UTC, mmphego commented on extract_unique_sensors_01.py
>  kat_sensor = "kat.sensors"
Why do you need to override the args you're passing in your script?

2020-07-29 08:03 UTC, mmphego commented on extract_unique_sensors_01.py
> +parser.add_argument('--url', help='Location of SensorList.txt')
This can be a function!

2020-07-29 08:06 UTC, mmphego commented on extract_unique_sensors_01.py
> +parser.add_argument('--url', help='Location of SensorList.txt')
The description of the argument is a bit confusing.
From [Wikipedia](https://en.wikipedia.org/wiki/URL), 
> A Uniform Resource Locator (URL), colloquially termed a web address,[1] is a reference to a web resource that specifies its location on a computer network and a mechanism for retrieving it. A URL is a specific type of Uniform Resource Identifier (URI),[2][3] although many people use the two terms interchangeably

2020-07-29 08:07 UTC, mmphego commented on extract_unique_sensors_01.py
> +parser.add_argument('--file_name', help='Actual name of the file')
```suggestion
parser.add_argument('--file_name', help='File to extract unique sensors from.')
```

2020-07-29 08:12 UTC, mmphego commented on extract_unique_sensors_01.py
> +    print(f'{args.file_name}, {args.url}, {args.kat_sensor}')
Is this for debugging?

2020-07-29 08:16 UTC, mmphego requested changes
You are on the right path, just need some minor changes.
:clap:

2020-07-29 12:33 UTC, mmphego commented on extract_unique_sensors_01.py
> +parser.add_argument('--url', help='Location of SensorList.txt')
@mamkhari

2020-07-30 15:33 UTC, mamkhari commented on extract_unique_sensors_01.py
>  kat_sensor = "kat.sensors"
I was not aware of that, but after re-running the script I noticed that this was not needed.

2020-07-30 16:29 UTC, mmphego commented on extract_unique_sensors_01.py
>  kat_sensor = "kat.sensors"
Please pay attention to detail, this is crucial. 
Every code commit should be reviewed by the author preferably before others review it. 

Always, think about: "What could go wrong?"

2020-08-05 14:48 UTC, mmphego approved these changes
Great job, this looks way better... :+1: 
Merge and update the Readme.md

2020-08-05 14:52 UTC, merged