Writing a line containing 'split' and 'strip' being used at the same …
mamkhari/extract_sensor_names pull request #3
Opened 2020-02-27 12:06 UTC by mamkhari

…time into two separate lines: first split the string then strip it in the next line.

2020-02-27 13:31 UTC, mmphego requested changes
Make the fixes as explained.

2020-02-27 13:31 UTC, mmphego commented on extract_unique_sensors.py
> +    sensor.strip("\n") # to remove newlines in a string
This has no effect, you are merely stripping of `\n` and not overwriting `sensor` variable.

This is what you should do instead:
`sensor = sensor.strip("\n")`

2020-02-27 13:31 UTC, mmphego commented on extract_unique_sensors.py
> +    sensor = sensor.split('.')[-1] # to split a string using a 'dot'character.
There should be 2 spaces before the beginning of the comment.

2020-02-28 07:48 UTC, mmphego commented on extract_unique_sensors.py
> +#  kat.sensors.anc_api_version   kat.sensors.anc_ganglia_api_version   kat.sensors.anc_ganglia_kat_monctl_system_os_name
wrt to spaces after `#`, please familiarize yourself with https://www.python.org/dev/peps/pep-0008/#id31

This is the sacred [style guide for Python](https://www.python.org/dev/peps/pep-0008), know it and breath it :laughing:

2020-02-28 07:48 UTC, mmphego commented on extract_unique_sensors.py
> +    sensor = sensor.strip("\n")  # to remove newlines in a string
Great improvement.

2020-02-28 07:48 UTC, mmphego commented on extract_unique_sensors.py
> +#  Loop over candidate_lines and extract sensor names
See: https://www.python.org/dev/peps/pep-0008/#id31

2020-02-28 07:49 UTC, mmphego requested changes
Almost there...

2020-02-28 08:51 UTC, mamkhari commented
> Almost there...

What's next?Merge the pull request?

2020-02-28 09:14 UTC, mmphego commented
> > Almost there...
> 
> What's next?Merge the pull request?

Please address the comments.

2020-02-28 09:15 UTC, mmphego commented on extract_unique_sensors.py
> +#  Loop over candidate_lines and extract sensor names
@mamkhari

2020-02-28 09:15 UTC, mmphego commented on extract_unique_sensors.py
> +#  kat.sensors.anc_api_version   kat.sensors.anc_ganglia_api_version   kat.sensors.anc_ganglia_kat_monctl_system_os_name
@mamkhari

2020-02-28 13:15 UTC, mmphego requested changes

2020-02-28 13:15 UTC, mmphego commented on extract_unique_sensors.py
> +  #  Loop over candidate_lines and extract sensor names
This is how it should be written.
```suggestion
# Loop over candidate_lines and extract sensor names 
```

2020-02-28 13:15 UTC, mmphego commented on extract_unique_sensors.py
> +  #  kat.sensors.anc_api_version   kat.sensors.anc_ganglia_api_version   kat.sensors.anc_ganglia_kat_monctl_system_os_name
```suggestion
    # Typical output from "sensor" variable:
    # kat.sensors.anc_api_version   kat.sensors.anc_ganglia_api_version   kat.sensors.anc_ganglia_kat_monctl_system_os_name
```

2020-02-28 14:37 UTC, mmphego approved these changes

2020-02-28 15:08 UTC, merged